# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Django CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r sobol/docker-django-react/backend/requirements.txt
      - name: Run tests
        run: python sobol/docker-django-react/backend/manage.py test